[build]
  # This command is essential to install Flask, Firebase, etc.
  command = "pip install -r requirements.txt"
  publish = "public"

  [build.environment]
  PYTHON_VERSION = "3.9"

[functions]
  directory = "netlify/functions"
  # DO NOT add the python_runtime line here

[[redirects]]
  # This makes your function available at yoursite.com/api/
  from = "/api/*"
  to = "/.netlify/functions/recipe-api/:splat"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"